### ISSUE TITLE
Multiworld not working

### ISSUE THREAD

**Issue by ctw452002** [iiFlamiinBlaze/BlazinJump#1]
I have turned on multi world support and changed the world
ex- 

#  ____  _            _______ _          _____
# |  _ \| |          |__   __| |        |  __ \
# | |_) | | __ _ _______| |  | |__   ___| |  | | _____   __
# |  _ <| |/ _` |_  / _ \ |  | '_ \ / _ \ |  | |/ _ \ \ / /
# | |_) | | (_| |/ /  __/ |  | | | |  __/ |__| |  __/\ V /
# |____/|_|\__,_/___\___|_|  |_| |_|\___|_____/ \___| \_/

# BlazinJump Configuration File:
#   Default Config:
#    jump-power: 1
#    multi-world: off
#    worlds:
#     - world

# The below config is the power of the double jump
jump-power: 1

# The below config is to turn on or off multi world support (OPTIONS: on and off)
multi-world: on

# The below config are the worlds in which BlazinJump will work in
worlds:
 - "Hub"

I still can double jump at other worlds

**Comment by iiFlamiinBlaze** [comment]
Hmm I’ll take a look at it

**Comment by ctw452002** [comment]
thx
