### ISSUE TITLE
multiworld not working

### ISSUE THREAD

**Issue by ctw452002** [iiFlamiinBlaze/BlazinJump#2]
I still can double jump in other world after new updates

**Comment by iiFlamiinBlaze** [comment]
Turn on multi-world support

**Comment by ctw452002** [comment]
Heres my currently resources


#  ____  _            _______ _          _____
# |  _ \| |          |__   __| |        |  __ \
# | |_) | | __ _ _______| |  | |__   ___| |  | | _____   __
# |  _ <| |/ _` |_  / _ \ |  | '_ \ / _ \ |  | |/ _ \ \ / /
# | |_) | | (_| |/ /  __/ |  | | | |  __/ |__| |  __/\ V /
# |____/|_|\__,_/___\___|_|  |_| |_|\___|_____/ \___| \_/

# BlazinJump Configuration File:
#   Default Config:
#    jump-power: 1
#    multi-world: "on"
#    worlds:
#     - "Hub"

# The below config is the power of the double jump
jump-power: 1

# The below config is to turn on or off multi world support (OPTIONS: on and off)
multi-world: "on"

# The below config are the worlds in which BlazinJump will work in
worlds:
 - "Hub"

**Comment by xXNiceYT** [comment]
Set multi-world: "on" to multi-world: "off"

**Comment by ctw452002** [comment]
ok let me try

**Comment by ctw452002** [comment]
Nvm its working I have 2resources and i used the faked one so its not working. It should be on btw @xXNiceYT

**Comment by iiFlamiinBlaze** [comment]
Lmao
